name: headless-wp

services:
  db:
    image: mysql:8.0
    container_name: headless-wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./wordpress
    container_name: headless-wp-wp
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../wordpress:/var/www/html
      - wordpress_uploads:/var/www/html/web/app/uploads
    depends_on:
      - db

volumes:
  db_data:
    name: headless-wp-db-data
  wordpress_uploads:
    name: headless-wp-wp-uploads